%% Import data from text file.
% Script for importing data from the following text file:
%
%    /users/eleves-a/2017/romain.lenoble/matlab/Microlens_Mera/table7.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/13 10:32:40

%% Initialize variables.
filename = '/users/eleves-a/2017/romain.lenoble/matlab/Microlens_Mera/table7.dat';

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%6s%9s%9s%5s%5s%5s%5s%6s%5s%5s%5s%4s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Create output variable
table1 = table;
table1.BLG500 = cell2mat(raw(:, 1));
table1.glon = cell2mat(raw(:, 2));
table1.glat = cell2mat(raw(:, 3));
table1.tau= cell2mat(raw(:, 4));
table1.tau_err= cell2mat(raw(:, 5));
table1.gam = cell2mat(raw(:, 6));
table1.gal_err= cell2mat(raw(:, 7));
table1.gam_deg2 = cell2mat(raw(:, 8));
table1.gam_deg2_err = cell2mat(raw(:, 9));
table1.t_E_mean = cell2mat(raw(:, 10));
table1.t_E_mean_err = cell2mat(raw(:, 11));
table1.N_events = cell2mat(raw(:, 12));
table1.N_stars  = cell2mat(raw(:, 13));

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp;


%% Dispaly

x = fliplr(table1.glon);
y = table1.glat;
sz = 200;
c = table1.tau;
figure(1)
scatter(x,y,sz,c,'d','filled')
colorbar



